- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0eb809a27bee0eadc
    sg_id: sg-0484fee2a20ead989
    ami_id: ami-09c813fb71547fc4f
    instance_type: t2.micro
    
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info
  - name: To print the output
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"