- name: create ec2 and r53 records
  connection: local
  hosts: local
  tasks:
  vars: 
   subnet_id: subnet-0eb809a27bee0eadc
   sg_id: sg-0484fee2a20ead989
   ami_id: ami-09c813fb71547fc4f
   instance_type: t2.micro
   instances:
   - mysql
   - backend
   - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_id: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"