- name: To install mysql
  hosts: web
  become: yes
  tasks:
   - name: To install mysql
     ansible.builtin.package:
      name: mysql-server
      state: installed
   - name: To buit servcie
     ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
   - name: To connect mysql server
     community.mysql.mysql_info:
      login_user: root
      login_password: Expense@1
      login_host: mysql.mukunda.store
      register: mysql_info
   - name: To print the output
     ansible.builtin.debug:
      msg: " display {{ mysql_info }}"