- name: To install mysql
  hosts: web
  become: yes
  tasks:
   - name: To install mysql
     ansible.builtin.package:
      name: mysql-server
      state: started
   - name: To buit servcie
     ansible.builtin.service:
      name: mysqld
      service: started
       