- name: To install mysql
  hosts: local
  become: yes
  tasks:
   - name: To install mysql
     ansible.builtin.package:
      name: mysql
      state: started
   - name:To buit servcie
     ansible.builtin.service:
      name: mysql
      service: started
       