- name: To run and install nginx
  hosts: web
  become: yes
  tasks:
  - name: To install nginx
    ansible.buildin.package:
     name: nginx
     state: install
  - name: To start nginx
    ansible.buildin.service:
     name: nginx
     state: present
     enabled: yes
    
