- name: To run and install nginx
  hosts: web
  become: yes
  tasks:
    - name: To install nginx
      ansibe.built.in.package:
      name:
      nginx: install
      state: present
    - name:
      ansible.builtin.service:
      service: start
      state: present
