- name: To run and install nginx
  hosts: web
  become: yes
  tasks:
  - name: To install ngnix
      ansible.built.in.package:
      name: nginx
      state: present
  - name: To run ngnix
      name: nginx
      ansibe.built.in.service:
      state: started
      enabled: yes
    -
