- name: To install ingnix and run
  hosts: web
  become: yes
  tasks:
  - name: Install ngnix
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start service and run
    ansible.builtin.service:
      name: ngnix
      state: started
      enabled: yes

