- name: To refer the variable name
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
   - name: To print the display information
     ansible.builtin.debug:
      msg : "keerthi {{MUKUNDA}}, everyday {{EVERYDAY}} ,spending {{SPENDING}}"