- name : To print the value name
  hosts: local
  connection: local
  vars_files:
  
  - name: to print
    prompt: please eneter mukunda
  - name: spending
    prompt: Everyday spending
    private: false
  - name: Money
    prompt: Everyday spendiing mone
    tasks:
     - name: To display the information
       ansible.builtin.debug:
          msg: "keerthi {{MUKUNDA}}, everyday {{EVERYDAY}} ,spending {{SPENDING}}"
